"""empty message

Revision ID: 2a45dff07bed
Revises: b6fc47cb4421
Create Date: 2025-03-18 14:46:56.820876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a45dff07bed'
down_revision = 'b6fc47cb4421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Muchachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Muchachos_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Muchachos', ['Muchachos_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Muchachos_id')

    op.drop_table('Muchachos')
    # ### end Alembic commands ###
