"""empty message

Revision ID: 3d60f41ec37d
Revises: 2a45dff07bed
Create Date: 2025-03-20 14:01:48.708728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d60f41ec37d'
down_revision = '2a45dff07bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muchachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Muchachos')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muchachos_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_Muchachos_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'muchachos', ['muchachos_id'], ['id'])
        batch_op.drop_column('Muchachos_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Muchachos_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_Muchachos_id_fkey', 'Muchachos', ['Muchachos_id'], ['id'])
        batch_op.drop_column('muchachos_id')

    op.create_table('Muchachos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Muchachos_pkey')
    )
    op.drop_table('muchachos')
    # ### end Alembic commands ###
